// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrBWEz6-RKiHuiGE65qmEv1odbxP7Z__s',
    appId: '1:867735312671:web:a6de1225ab256f50a7382a',
    messagingSenderId: '867735312671',
    projectId: 'upscal-app',
    authDomain: 'upscal-app.firebaseapp.com',
    storageBucket: 'upscal-app.appspot.com',
    measurementId: 'G-H3DLD37GDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYANJVUEGWNg32zWqsNRVIxf1LLOGzTQ',
    appId: '1:867735312671:android:56ec4ed446e399a6a7382a',
    messagingSenderId: '867735312671',
    projectId: 'upscal-app',
    storageBucket: 'upscal-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUrVR3H1Rx-DZtWQLnUWl5ess1sBMbN8',
    appId: '1:867735312671:ios:daafefd5923cbf65a7382a',
    messagingSenderId: '867735312671',
    projectId: 'upscal-app',
    storageBucket: 'upscal-app.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvUrVR3H1Rx-DZtWQLnUWl5ess1sBMbN8',
    appId: '1:867735312671:ios:0e6d18c1a9a1bf4ca7382a',
    messagingSenderId: '867735312671',
    projectId: 'upscal-app',
    storageBucket: 'upscal-app.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
